commit_id = "15206881c006c79667fe5154fe80c01c65410679"
language = "python"
build_env = "conda create -n jinja-dev python==3.10 pytest pytest-cov trio"
build_repo = "pip install -e ."
dependencies = []
