commit_id = "d00a27df750130e28e4801caaedc782433863a37"
language = "python"
build_env = "conda create -n seaborn-dev python==3.10"
build_repo = [ "pip install flit_core click pytest==8.2", "python -m pip install --verbose --no-build-isolation --editable \".[dev]\"",]
dependencies = []
